COPY    START   1000		COPY FILE FROM INPUT TO OUTPUT
FIRST   STL     RETADR		SAVE RETURN ADDRESS
CLOOP   JSUB    RDREC		READ INPUT RECORD
	LDA	LENGTH		TEST FOR EOF (LENGTH = 0)


	LDA	LENGTH		TEST FOR EOF (LENGTH = 0)
	COMP    ZERO
	JEQ     ENDFIL		EXIT IF EOF FOUND
	JSUB	WRREC		WRITE OUTPUT RECORD
	J       CLOOP		LOOP
EOF     BYTE    CEOF'
THREE   WORD    3
THREE    WORD    0
RETADR  RESW    1
LENGTH  RESW    1		LENGTH OF RECORD
RLOOP   TD      INPUT		TEST INPUT DEVICE
	JEQ     RLOOP		LOOP UNTIL READY
	RD      INPUT		READ CHARACTER INTO REGISTAR A
	COMP    ZERO		TEST FOR END OF RECORD (X'00')
BUFFER  RESB    
BUFFER  RESB    AAA
.
WRREC   LDX    ZERO		CLEAR LOOP COUNTER
WLOOP   TD     OUTPUT		TEST OUTPUT DEVICE
	JEQ    WLOOP		LOOP UNTIL READY
	LDCH   BUFFER,X	        GET CHARCTER FROM BUFFER
	WD     OUTPUT		WRITE CHARACTER
	TIX    LENGTH		LOOP UNTIL ALL CHARACTERS
OUTPUT  BYTE   X'5'		CODE FOR OUTPUT DEVICE
AAKS	END    FIRST
