COPY    START   1000		COPY FILE FROM INPUT TO OUTPUT
FIRST   STL     RETADR		SAVE RETURN ADDRESS
CLOOP   JSUB    RDREC		READ INPUT RECORD
	LDA	LENGTH		TEST FOR EOF (LENGTH = 0)

EOF     BYTE    CEOF'
THREE   WORD    3
THREE    WORD    0
RETADR  RESW    1
LENGTH  RESW    1		LENGTH OF RECORD
BUFFER  RESB    
BUFFER  RESB    AAA
.

OUTPUT  BYTE   X'5'		CODE FOR OUTPUT DEVICE
AAKS	END    FIRST